services:
  redis-server:
    image: 'redis'
  loier:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - redis-server
    volumes:
      - .:/user/app/loier
    env_file:
      - .env