services:
  redis-server:
    image: 'redis'
  loier:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis-server
    volumes:
      - .:/user/app/loier